### ISSUE TITLE
Ошибка при установке интеграции

### ISSUE THREAD

**Issue by kamulchik** [Pshatsillo/mega_hacs#1]
**Описание**
Обновил HA до 2024.10.4
Заменил интеграцию andvikt на Pshatsillo
По этой инструкции
https://github.com/Pshatsillo/mega_hacs/blob/master/install.sh
Предварительно удалив из custom_components интеграции от andvikt
Интеграция перестала запускаться

**Версии систем**
Enviroment: docker
HA version: 2024.10.4
mega_hacs version:
megad firmware version:
используется mqtt: false

**Ожидаемое поведение**
Интеграция будет работать

2024-10-31 13:55:00.388 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry mega for mega
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 933, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mega/__init__.py", line 268, in async_migrate_entry
    config_entry.data = new
    ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in __setattr__
    raise AttributeError(
AttributeError: data cannot be changed directly, use async_update_entry instead

**Comment by Pshatsillo** [comment]
Попробуйте снова

**Comment by kamulchik** [comment]
> Попробуйте снова

Такая же ошибка.

2024-11-11 16:30:51.102 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry mega3 for mega
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 933, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mega/__init__.py", line 268, in async_migrate_entry
    await async_update_entry(hass, config_entry)
  File "/config/custom_components/mega/__init__.py", line 284, in async_update_entry
    config_entry.data = new
    ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in __setattr__
    raise AttributeError(
AttributeError: data cannot be changed directly, use async_update_entry instead
2024-11-11 16:30:51.384 WARNING (MainThread) [custom_components.mega.mega2] can not add ds2413 on port 30, it has wrong data: {'value': ''}
2024-11-11 16:30:51.503 DEBUG (influxdb) [homeassistant.components.influxdb] Wrote 9 events.
2024-11-11 16:30:51.701 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry mega for mega
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 933, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mega/__init__.py", line 268, in async_migrate_entry
    await async_update_entry(hass, config_entry)
  File "/config/custom_components/mega/__init__.py", line 284, in async_update_entry
    config_entry.data = new
    ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in __setattr__
    raise AttributeError(
AttributeError: data cannot be changed directly, use async_update_entry instead

**Comment by kamulchik** [comment]
Похоже что это всё из одного корня и нужно ждать релиз HA.
https://github.com/home-assistant/core/issues/130174

**Comment by kamulchik** [comment]
Работает, спасибо!
