### ISSUE TITLE
Не работает настройка интегрции

### ISSUE THREAD

**Issue by kamulchik** [Pshatsillo/mega_hacs#4]
**Описание**
Заменил интеграцию andvikt на Pshatsillo
По этой инструкции
https://github.com/Pshatsillo/mega_hacs/blob/master/install.sh
Предварительно удалив из custom_components интеграции от andvikt
Интеграция запустилась, датчики работают, переключение света также. Но не могу зайти в настройки для обновления объектов.

**Версии систем**
Enviroment: docker
HA version: 2024.10.4
mega_hacs version:
megad firmware version:
используется mqtt: false

**Ожидаемое поведение**
Появится меню настроек интеграции

**Screenshots**
![image](https://github.com/user-attachments/assets/60718ea6-90b5-4ced-80b2-a6f254640b9a)

**LOG**
```
2024-11-14 16:15:45.692 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 262, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 77, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 345, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mega/config_flow.py", line 114, in async_step_init
    new_naming = self.config_entry.data.get('new_naming', False)
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'OptionsFlowHandler' object has no attribute 'config_entry'
```

**Comment by Dasisfakt** [comment]
Присоединюсь, та же ошибка.

**Comment by latishev** [comment]
Аналогично и у меня. Я я бы перенес конфиг интеграции вручную, если кто-то подскажет как это сделать. Настроить заново с нуля нереально, десяток моноблоков, сотни портов.

**Comment by Dasisfakt** [comment]
Отлично, заработало!

**Comment by Nik-Targon** [comment]
Способ установки
Home Assistant Supervised
Core
2026.2.3
Supervisor
2026.02.2
Operating System
Frontend
20260128.6

Полностью удалил интеграцию, из custom_compontents  установил заново через hacs,  заново создал устройство с тем-же идентификатором что и ранее  md01  устройства все подтянулись, но  ошибка осталась Не удалось загрузить мастер настройки: 500 Internal Server Error Server got itself in trouble.

Также в логе вижу 
Регистратор: homeassistant.components.light
Источник: helpers/deprecation.py:257
интеграция: Освещение (документация, проблемы)
Зафиксировано первый раз: 12:55:42 (2 случая)
Зафиксировано последний раз: 12:55:42

The deprecated constant SUPPORT_COLOR was used from mega. It will be removed in HA Core 2026.1. Use supported_color_modes instead, please report it to the author of the 'mega' custom integration


Также   после переустановки интеграции перестал включаться свет с кнопки, он кратковременно моргает и выключается
